version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    groups:
      release-credentials:
        patterns:
          - "rust-lang/crates-io-auth-action"
          - "release-plz/action"
          - "sigstore/cosign-installer"
          - "softprops/action-gh-release"
      actions:
        patterns: ["*"]
